import { useEffect, useState } from 'react';
import Nav from '../../components/Nav/Nav';
import Card from '../../components/Card/Card';
import DefaultLayout from '../../layout/Default';
import Head from 'next/head';

const Cats = () => {
	const [cats, setCats] = useState([]);

	const fetchCats = async () => {
		const response = await fetch(`/api/cats`);
		const data = await response.json();
		setCats(data);
	};

	useEffect(() => {
		fetchCats();
	}, []);

	return (
		<>
			<Head>
				<title>Our Cats</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<DefaultLayout>
				<div className='container mt-5'>
					<div
						style={{
							display: 'flex',
							flexWrap: 'wrap',
							justifyContent: 'space-between',
						}}
					>
						{cats.map((cat) => (
							<Card
								key={cat.id}
								name={cat.name}
								id={cat.id}
								phone={cat.phone}
								email={cat.email}
								image={cat.image}
							/>
						))}
					</div>
				</div>
			</DefaultLayout>
		</>
	);
};

export default Cats;
